default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: car_rental_development

test:
  <<: *default
  database: car_rental_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
