default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: "24434"

development:
  <<: *default
  database: car_rental_development
  username: postgres
  password: "24434"

test:
  <<: *default
  database: car_rental_test
  username: postgres
  password: "24434"

production:
  <<: *default
  database: car_rental_production
